apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: revenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revenge
  template:
    metadata:
      labels:
        app: revenge
    spec:
      containers:
      - name: revenge
        image: jeffjerseycow/revenge:201810-v0.0.7
        ports:
        - name: alt-https
          containerPort: 8443
        env:
        - name: REVENGE_FLAG
          valueFrom:
            secretKeyRef:
              name: flags
              key: revenge
      - name: revenge-web
        image: jeffjerseycow/revenge-web:201810-v0.0.6
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: revenge-service
spec:
  selector:
    app: revenge
  ports:
  - name: alt-https
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
