apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: lovectf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lovectf
  template:
    metadata:
      labels:
        app: lovectf
    spec:
      containers:
      - name: lovectf
        image: jeffjerseycow/lovectf:v0.0.1
        ports:
        - name: alt-https
          containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: lovectf-service
spec:
  selector:
    app: lovectf
  ports:
  - name: alt-https
    protocol: TCP
    port: 8443
    targetPort: 8443
  type: LoadBalancer
